# Generated by Django 5.2.14 on 2026-05-11 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('brand_color', models.CharField(default='#6366F1', help_text='Hex incl. leading #', max_length=9)),
                ('logo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='beoweek',
            name='week_start',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=40)),
                ('client_org', models.CharField(blank=True, help_text="Client's company name (free text)", max_length=120)),
                ('event_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('corporate', 'Corporate'), ('wedding', 'Wedding'), ('conference', 'Conference'), ('social', 'Social / Private'), ('nonprofit', 'Nonprofit / Fundraiser'), ('other', 'Other')], default='corporate', max_length=20)),
                ('preferred_date', models.DateField()),
                ('alternate_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('headcount', models.PositiveIntegerField()),
                ('venue_preference', models.CharField(blank=True, max_length=200)),
                ('food_service', models.CharField(choices=[('none', 'No food service'), ('light', 'Light bites / snacks'), ('plated', 'Plated meal'), ('buffet', 'Buffet'), ('cocktail', 'Cocktail-style passed apps')], default='none', max_length=20)),
                ('dietary_notes', models.TextField(blank=True)),
                ('tech_needs', models.CharField(choices=[('none', 'None'), ('basic_av', 'Basic A/V (mic + speakers)'), ('full_av', 'Full A/V (projector, screen, mixer)'), ('livestream', 'Livestream / hybrid')], default='none', max_length=20)),
                ('rsvp_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('completed', 'Completed')], default='new', max_length=20)),
                ('organizer_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_user', models.ForeignKey(blank=True, help_text='Set if a logged-in client submitted; null for anonymous.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Planner org receiving the request. Null = legacy/unrouted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_requests', to='api.organization')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='beoweek',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beo_weeks', to='api.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='beoweek',
            unique_together={('organization', 'week_start')},
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('role', models.CharField(choices=[('coordinator', 'Coordinator'), ('chef', 'Chef'), ('bartender', 'Bartender'), ('server', 'Server'), ('it', 'IT / A/V'), ('setup', 'Setup Crew'), ('security', 'Security'), ('vendor', 'Vendor'), ('other', 'Other')], default='other', max_length=20)),
                ('is_vendor', models.BooleanField(default=False)),
                ('company', models.CharField(blank=True, help_text='For third-party vendors', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='api.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_on_event', models.CharField(blank=True, help_text='e.g. "Lead Bartender"', max_length=80)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='assigned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('event_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.eventrequest')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.teammember')),
            ],
            options={
                'ordering': ['assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('planner', 'Event Planner')], default='client', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='api.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('trigger', models.CharField(choices=[('on_submit', 'Event request submitted'), ('on_status_new', 'Status changed → New'), ('on_status_in_review', 'Status changed → In Review'), ('on_status_confirmed', 'Status changed → Confirmed'), ('on_status_declined', 'Status changed → Declined'), ('on_status_completed', 'Status changed → Completed')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='api.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('action_type', models.CharField(choices=[('send_email', 'Send email'), ('add_organizer_note', 'Append organizer note'), ('set_status', 'Change status')], max_length=40)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.workflow')),
            ],
            options={
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_name', models.CharField(blank=True, help_text='Snapshot of workflow.name at run time.', max_length=120)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('log', models.TextField(blank=True)),
                ('event_request', models.ForeignKey(help_text='Null if the event request has since been deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='api.eventrequest')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='api.organization')),
                ('workflow', models.ForeignKey(help_text='Null if the source workflow has since been deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='api.workflow')),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('table', 'Tables'), ('chair', 'Chairs'), ('food', 'Food'), ('beverage', 'Beverages'), ('av', 'A/V Equipment'), ('linen', 'Linens'), ('serviceware', 'Serviceware'), ('other', 'Other')], default='other', max_length=20)),
                ('unit', models.CharField(blank=True, help_text='each, lb, gallon, etc.', max_length=40)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('low_stock_threshold', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='api.organization')),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['organization', 'category'], name='api_invento_organiz_40d433_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='eventrequest',
            index=models.Index(fields=['organization', 'status'], name='api_eventre_organiz_6f6d22_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrequest',
            index=models.Index(fields=['organization', '-submitted_at'], name='api_eventre_organiz_cb477f_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['organization', 'role'], name='api_teammem_organiz_b0d8a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventassignment',
            unique_together={('event_request', 'team_member', 'role_on_event')},
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['organization', 'trigger', 'is_active'], name='api_workflo_organiz_f151f3_idx'),
        ),
    ]
