# Generated by Django 5.2.14 on 2026-05-11 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=40)),
                ('organization', models.CharField(blank=True, max_length=120)),
                ('event_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('corporate', 'Corporate'), ('wedding', 'Wedding'), ('conference', 'Conference'), ('social', 'Social / Private'), ('nonprofit', 'Nonprofit / Fundraiser'), ('other', 'Other')], default='corporate', max_length=20)),
                ('preferred_date', models.DateField()),
                ('alternate_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('headcount', models.PositiveIntegerField()),
                ('venue_preference', models.CharField(blank=True, max_length=200)),
                ('food_service', models.CharField(choices=[('none', 'No food service'), ('light', 'Light bites / snacks'), ('plated', 'Plated meal'), ('buffet', 'Buffet'), ('cocktail', 'Cocktail-style passed apps')], default='none', max_length=20)),
                ('dietary_notes', models.TextField(blank=True)),
                ('tech_needs', models.CharField(choices=[('none', 'None'), ('basic_av', 'Basic A/V (mic + speakers)'), ('full_av', 'Full A/V (projector, screen, mixer)'), ('livestream', 'Livestream / hybrid')], default='none', max_length=20)),
                ('rsvp_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('completed', 'Completed')], default='new', max_length=20)),
                ('organizer_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('table', 'Tables'), ('chair', 'Chairs'), ('food', 'Food'), ('beverage', 'Beverages'), ('av', 'A/V Equipment'), ('linen', 'Linens'), ('serviceware', 'Serviceware'), ('other', 'Other')], default='other', max_length=20)),
                ('unit', models.CharField(blank=True, help_text='each, lb, gallon, etc.', max_length=40)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('low_stock_threshold', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('role', models.CharField(choices=[('coordinator', 'Coordinator'), ('chef', 'Chef'), ('bartender', 'Bartender'), ('server', 'Server'), ('it', 'IT / A/V'), ('setup', 'Setup Crew'), ('security', 'Security'), ('vendor', 'Vendor'), ('other', 'Other')], default='other', max_length=20)),
                ('is_vendor', models.BooleanField(default=False)),
                ('company', models.CharField(blank=True, help_text='For third-party vendors', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('trigger', models.CharField(choices=[('on_submit', 'Event request submitted'), ('on_status_new', 'Status changed → New'), ('on_status_in_review', 'Status changed → In Review'), ('on_status_confirmed', 'Status changed → Confirmed'), ('on_status_declined', 'Status changed → Declined'), ('on_status_completed', 'Status changed → Completed')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('action_type', models.CharField(choices=[('send_email', 'Send email'), ('add_organizer_note', 'Append organizer note'), ('set_status', 'Change status')], max_length=40)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.workflow')),
            ],
            options={
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('log', models.TextField(blank=True)),
                ('event_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='api.eventrequest')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.workflow')),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
        migrations.CreateModel(
            name='EventAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_on_event', models.CharField(blank=True, help_text='e.g. "Lead Bartender"', max_length=80)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='assigned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('event_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.eventrequest')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.teammember')),
            ],
            options={
                'ordering': ['assigned_at'],
                'unique_together': {('event_request', 'team_member', 'role_on_event')},
            },
        ),
    ]
