# Generated by Django 5.2.14 on 2026-05-12 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_organization_alter_beoweek_week_start_authtoken_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor'), ('both', 'Client + Vendor')], default='client', max_length=10)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('services', models.JSONField(blank=True, default=list, help_text='Vendor-only: e.g. ["catering", "florals"]')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(blank=True, help_text='Default title; can be overridden per-company', max_length=120)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactCompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(blank=True, help_text='e.g. "Events Lead", "Owner"', max_length=120)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact at this company')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_primary', 'company__name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('corporate', 'Corporate'), ('wedding', 'Wedding'), ('conference', 'Conference'), ('social', 'Social / Private'), ('nonprofit', 'Nonprofit / Fundraiser'), ('other', 'Other')], default='corporate', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('headcount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('food_service', models.CharField(choices=[('none', 'No food service'), ('light', 'Light bites / snacks'), ('plated', 'Plated meal'), ('buffet', 'Buffet'), ('cocktail', 'Cocktail-style passed apps')], default='none', max_length=20)),
                ('tech_needs', models.CharField(choices=[('none', 'None'), ('basic_av', 'Basic A/V (mic + speakers)'), ('full_av', 'Full A/V (projector, screen, mixer)'), ('livestream', 'Livestream / hybrid')], default='none', max_length=20)),
                ('rsvp_required', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='Optional calendar tint', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('unit', models.CharField(blank=True, help_text='each, lb, gallon, etc.', max_length=40)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text="Org's cost basis per unit", max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Charge-to-client per unit', max_digits=10)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('table', 'Tables'), ('chair', 'Chairs'), ('linen', 'Linens'), ('serviceware', 'Serviceware (plates, glasses, flatware)'), ('av', 'A/V Equipment'), ('lighting', 'Lighting'), ('staging', 'Staging / Risers'), ('decor', 'Decor / Props'), ('heating', 'Heating / Cooling'), ('other', 'Other')], default='other', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('needs_repair', 'Needs repair'), ('retired', 'Retired')], default='good', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=80)),
                ('storage_location', models.CharField(blank=True, help_text='Where it lives when not deployed', max_length=120)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_serviced', models.DateField(blank=True, null=True)),
                ('service_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('beo', 'BEO (Banquet Event Order)'), ('guest_email', 'Guest notification (email)'), ('guest_sms', 'Guest notification (SMS)'), ('vendor_email', 'Vendor notification (email)'), ('vendor_sms', 'Vendor notification (SMS)'), ('internal_email', 'Internal team email'), ('contract', 'Contract / Agreement'), ('invoice', 'Invoice'), ('other', 'Other')], default='guest_email', max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('pdf', 'Printable PDF')], default='email', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True, help_text='Use {{tokens}} — see docs for available tokens')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='One default per (kind, channel)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Perishable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('unit', models.CharField(blank=True, help_text='each, lb, gallon, etc.', max_length=40)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text="Org's cost basis per unit", max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Charge-to-client per unit', max_digits=10)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('produce', 'Produce'), ('protein', 'Protein / Meat / Seafood'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('dry_goods', 'Dry goods'), ('beverage', 'Beverages'), ('alcohol', 'Alcohol'), ('garnish', 'Garnish / Mixers'), ('other', 'Other')], default='other', max_length=20)),
                ('storage', models.CharField(choices=[('pantry', 'Pantry / Room temp'), ('cooler', 'Refrigerated'), ('freezer', 'Frozen'), ('cellar', 'Cellar / Wine room')], default='pantry', max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=160)),
                ('lot_number', models.CharField(blank=True, max_length=80)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('last_restocked', models.DateField(blank=True, null=True)),
                ('allergens', models.JSONField(blank=True, default=list, help_text='e.g. ["gluten","dairy","nuts"]')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state_region', models.CharField(blank=True, max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('owner_name', models.CharField(blank=True, max_length=160)),
                ('operator_name', models.CharField(blank=True, help_text='Who runs the day-to-day (often = owner)', max_length=160)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('capacity_min', models.PositiveIntegerField(default=0)),
                ('capacity_max', models.PositiveIntegerField(default=0)),
                ('square_footage', models.PositiveIntegerField(default=0, help_text='0 = unknown')),
                ('supported_layouts', models.JSONField(blank=True, default=list, help_text='Subset of LAYOUT_CHOICES values')),
                ('has_av', models.BooleanField(default=False)),
                ('has_stage', models.BooleanField(default=False)),
                ('has_dance_floor', models.BooleanField(default=False)),
                ('has_kitchen_access', models.BooleanField(default=False)),
                ('has_outdoor_access', models.BooleanField(default=False)),
                ('is_accessible', models.BooleanField(default=True, help_text='ADA / wheelchair accessible')),
                ('has_natural_light', models.BooleanField(default=False)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('base_hourly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Org-internal cost baseline; 0 = unset', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['site__name', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='organization',
        ),
        migrations.RemoveIndex(
            model_name='teammember',
            name='api_teammem_organiz_b0d8a2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='eventassignment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='company',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='is_vendor',
        ),
        migrations.AddField(
            model_name='eventassignment',
            name='staff_count',
            field=models.PositiveIntegerField(default=1, help_text='For vendor assignments: # of vendor staff on-site'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teammember',
            name='employment_type',
            field=models.CharField(choices=[('staff', 'Staff (W-2)'), ('temp', 'Temp / Contractor')], default='staff', max_length=10),
        ),
        migrations.AddField(
            model_name='teammember',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Org-internal cost; 0 = unset', max_digits=8),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventassignment',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.teammember'),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='client_org',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_requests', to='api.organization'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('coordinator', 'Coordinator'), ('chef', 'Chef'), ('bartender', 'Bartender'), ('server', 'Server'), ('it', 'IT / A/V'), ('setup', 'Setup Crew'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='event_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='api.eventrequest'),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='api.workflow'),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='workflow_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['organization', 'role', 'employment_type'], name='api_teammem_organiz_49c971_idx'),
        ),
        migrations.AddField(
            model_name='company',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='api.organization'),
        ),
        migrations.AddField(
            model_name='eventassignment',
            name='vendor_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to='api.company'),
        ),
        migrations.AddConstraint(
            model_name='eventassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('team_member__isnull', False)), fields=('event_request', 'team_member', 'role_on_event'), name='uniq_team_assignment'),
        ),
        migrations.AddConstraint(
            model_name='eventassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor_company__isnull', False)), fields=('event_request', 'vendor_company'), name='uniq_vendor_assignment'),
        ),
        migrations.AddConstraint(
            model_name='eventassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('team_member__isnull', False), ('vendor_company__isnull', True)), models.Q(('team_member__isnull', True), ('vendor_company__isnull', False)), _connector='OR'), name='exactly_one_assignee'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.organization'),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_requests', to='api.contact'),
        ),
        migrations.AddField(
            model_name='contactcompanyrole',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
        migrations.AddField(
            model_name='contactcompanyrole',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='contacts', through='api.ContactCompanyRole', to='api.company'),
        ),
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.contact'),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.organization'),
        ),
        migrations.AddField(
            model_name='event',
            name='source_request',
            field=models.ForeignKey(blank=True, help_text='The intake request that became this event. Null for planner-created events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.eventrequest'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to='api.organization'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='api.organization'),
        ),
        migrations.AddField(
            model_name='perishable',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perishables', to='api.organization'),
        ),
        migrations.AddField(
            model_name='site',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='api.organization'),
        ),
        migrations.AddField(
            model_name='sitevenue',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='api.site'),
        ),
        migrations.AddField(
            model_name='event',
            name='site_venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.sitevenue'),
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['organization', 'kind'], name='api_company_organiz_93daf0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactcompanyrole',
            unique_together={('contact', 'company')},
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'last_name', 'first_name'], name='api_contact_organiz_790309_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'email'], name='api_contact_organiz_71daba_idx'),
        ),
        migrations.AddIndex(
            model_name='hardware',
            index=models.Index(fields=['organization', 'category'], name='api_hardwar_organiz_af487b_idx'),
        ),
        migrations.AddIndex(
            model_name='hardware',
            index=models.Index(fields=['organization', 'condition'], name='api_hardwar_organiz_9336c3_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['organization', 'kind', 'is_active'], name='api_message_organiz_3e8a37_idx'),
        ),
        migrations.AddIndex(
            model_name='perishable',
            index=models.Index(fields=['organization', 'category'], name='api_perisha_organiz_87d7fc_idx'),
        ),
        migrations.AddIndex(
            model_name='perishable',
            index=models.Index(fields=['organization', 'expiry_date'], name='api_perisha_organiz_50fd74_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['organization', 'name'], name='api_site_organiz_21b1e6_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevenue',
            index=models.Index(fields=['site', 'is_active'], name='api_siteven_site_id_a6d82b_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'starts_at'], name='api_event_organiz_f192d2_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'status'], name='api_event_organiz_585596_idx'),
        ),
    ]
